#!/bin/sh

# SPDX-FileCopyrightText: 2026 Project516 <138796702+Project516@users.noreply.github.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

set -e

# Make the game executable
chmod +x /usr/games/numberguessinggame

exit 0
