#!/bin/sh

# SPDX-FileCopyrightText: 2026 Project516 <138796702+Project516@users.noreply.github.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# Wrapper script to launch Number Guessing Game

java -jar /usr/share/games/numberguessinggame/game.jar "$@"
