/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.project516.NumberGuessingGame;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

class SystemInfoTest {
    @Test
    void jdkIsHere() {
        SystemInfo classUnderTest = new SystemInfo();
        assertNotNull(classUnderTest.vendor(), "expect output!");
    }
}
